export type ShadowTypes = "xxs" | "xs" | "sm" | "default" | "md" | "lg" | "xlg" | "xxlg";

export type RadiusTypes = "none" | "sm" | "md" | "lg" | "xl" | "pill" | "full";

export type BorderTypes = "none" | "sm" | "default" | "lg";

export type BorderPosition = "top" | "left" | "right" | "bottom" | "all";

export type SpacingTypes = "xxs" | "xs" | "sm" | "default" | "md" | "lg" | "xlg" | "xxlg";

export type SpacingDirections = "all" | "horizontal" | "vertical";

export type LetterSpacingTypes = "xxs" | "xs" | "sm" | "default" | "md" | "lg" | "xlg";

export type LineHeightsTypes = "none" | "shorther" | "short" | "base" | "tall" | "taller";

export type FontSizeTypes = "xxxs" | "xxs" | "xs" | "sm" | "md" | "lg" | "xl" | "xxl" | "xxxl" | "display";

export type FontFaceTypes =
    | "primary"
    | "secondary"
    | "tertiary"
    | "custom1"
    | "custom2"
    | "custom3"
    | "custom4"
    | "custom5";

export type TextAlignTypes = "left" | "right" | "center" | "justify";

export type FontWeightTypes =
    | "hairline"
    | "thin"
    | "light"
    | "normal"
    | "medium"
    | "semibold"
    | "bold"
    | "extrabold"
    | "black";

export type ColorTypes =
    | "primary"
    | "primaryGradient"
    | "primaryShade"
    | "primaryTint"
    | "primaryContrast"
    | "secondary"
    | "secondaryGradient"
    | "secondaryShade"
    | "secondaryTint"
    | "secondaryContrast"
    | "tertiary"
    | "tertiaryGradient"
    | "tertiaryShade"
    | "tertiaryTint"
    | "tertiaryContrast"
    | "success"
    | "successGradient"
    | "successShade"
    | "successTint"
    | "successContrast"
    | "warning"
    | "warningGradient"
    | "warningShade"
    | "warningTint"
    | "warningContrast"
    | "danger"
    | "dangerGradient"
    | "dangerShade"
    | "dangerTint"
    | "dangerContrast"
    | "dark"
    | "darkGradient"
    | "darkShade"
    | "darkTint"
    | "darkContrast"
    | "medium"
    | "mediumGradient"
    | "mediumShade"
    | "mediumTint"
    | "mediumContrast"
    | "light"
    | "lightGradient"
    | "lightTint"
    | "lightShade"
    | "lightContrast"
    | "divider"
    | "background"
    | "gray"
    | "transparent"
    | "black"
    | "white"
    | "text"
    | "custom1"
    | "custom1Gradient"
    | "custom1Shade"
    | "custom1Tint"
    | "custom1Contrast"
    | "custom2"
    | "custom2Gradient"
    | "custom2Shade"
    | "custom2Tint"
    | "custom2Contrast"
    | "custom3"
    | "custom3Gradient"
    | "custom3Shade"
    | "custom3Tint"
    | "custom3Contrast"
    | "custom4"
    | "custom4Gradient"
    | "custom4Shade"
    | "custom4Tint"
    | "custom4Contrast"
    | "custom5"
    | "custom5Gradient"
    | "custom5Shade"
    | "custom5Tint"
    | "custom5Contrast"
    | "custom6"
    | "custom6Gradient"
    | "custom6Shade"
    | "custom6Tint"
    | "custom6Contrast"
    | "custom7"
    | "custom7Gradient"
    | "custom7Shade"
    | "custom7Tint"
    | "custom7Contrast"
    | "custom8"
    | "custom8Gradient"
    | "custom8Shade"
    | "custom8Tint"
    | "custom8Contrast"
    | "custom9"
    | "custom9Gradient"
    | "custom9Shade"
    | "custom9Tint"
    | "custom9Contrast"
    | "custom10"
    | "custom10Gradient"
    | "custom10Shade"
    | "custom10Tint"
    | "custom10Contrast"
    | "custom11"
    | "custom11Gradient"
    | "custom11Shade"
    | "custom11Tint"
    | "custom11Contrast"
    | "custom12"
    | "custom12Gradient"
    | "custom12Shade"
    | "custom12Tint"
    | "custom12Contrast"
    | "custom13"
    | "custom13Gradient"
    | "custom13Shade"
    | "custom13Tint"
    | "custom13Contrast"
    | "custom14"
    | "custom14Gradient"
    | "custom14Shade"
    | "custom14Tint"
    | "custom14Contrast"
    | "custom15"
    | "custom15Gradient"
    | "custom15Shade"
    | "custom15Tint"
    | "custom15Contrast";
