name: Create Storybook Documentation
on:
    push:
        branches:
            - main
jobs:
    storybook-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Install and Build
              working-directory: ./packages/core
              run: |
                  yarn
                  yarn build-storybook

            - name: Deploy
              working-directory: ./packages/core
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  branch: gh-pages
                  folder: storybook-static
