name: Release NPM Package
on:
    push:
        branches:
            - alpha
jobs:
    release:
        name: Release Alpha
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip-package]')"
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              env: 
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_SEMANTIC_TOKEN }}
              with:
                  node-version: "14.x"
                  always-auth: true
                  registry-url: "https://registry.npmjs.org"
            - name: Install dependencies
              working-directory: ./packages/core
              run: | 
                yarn
                yarn build
            - name: Release package
              working-directory: ./packages/core
              run: yarn publish:npm
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_SEMANTIC_TOKEN }}
