name: Release NPM Package
on:
    push:
        branches:
            - main
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_SEMANTIC_TOKEN }}
              with:
                  node-version: "12.x"
                  always-auth: true
                  registry-url: "https://registry.npmjs.org"
            - name: Install dependencies
              run: yarn
            - name: Build distribution package
              run: yarn build
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_SEMANTIC_TOKEN }}
              run: npx semantic-release
